componentScriptContent: 
  - xmlizable: 
    - â†‘classname: com.twinsoft.convertigo.beans.common.FormatedContent
    - com.twinsoft.convertigo.beans.common.FormatedContent: 
      â†’: |
        /*Begin_c8o_AppImport*/
        import {enableProdMode} from '@angular/core';
        enableProdMode();
        /*End_c8o_AppImport*/
        /*Begin_c8o_AppDeclaration*/
        	/*End_c8o_AppDeclaration*/
        /*Begin_c8o_AppSettings*/
                /*End_c8o_AppSettings*/
        /*Begin_c8o_AppConstructor*/
        		/*End_c8o_AppConstructor*/
        /*Begin_c8o_AppInitialization*/
                        c8o.logLevelLocal = C8oLogLevel.DEBUG;
                        c8o.logC8o = true; //dz,dnz
                        /* Uncomment the following lines to enable the i18n feature.
                         * You should add a json per language in the assets/i18n folder. */
                        let localLang = window.localStorage.getItem("lang");
                        if(localLang !=  undefined){
                            this.translate.setDefaultLang(localLang);
                        }
                        else{
                            this.translate.setDefaultLang('en');
                        }
                        this.global["platform"] = {};
                        this.global["platform"]["width"] = platform.width();
                        this.global["platform"]["info"] = platform.platforms();
                        this.global["platform"]["name"] = [""]
                        if(platform.platforms()[0] == "android" || platform.platforms()[0] == "cordova" || platform.platforms()[0] == "mobile" || platform.platforms()[0] == "ios" ){
                            this.global["platform"]["name"][0] =  "mobile";
                        }
                        //console.log(this.global["platform"]["name"][0]);
                        /*
                        (this.app.getActiveNav() as 
                        // translate.use(translate.getBrowserLang());
                        
                        /* Uncomment the following lines to enable the custom status bar color. */
                        // statusBar.overlaysWebView(false);
                        // statusBar.backgroundColorByHexString("#000000");
                        // statusBar.styleBlackOpaque();
        			/*End_c8o_AppInitialization*/
        /*Begin_c8o_AppFunction*/
        	/*End_c8o_AppFunction*/
        /*Begin_c8o_function:CTS1559834148370*/
        		page.c8o.log.debug(event ? event.toString():'no event');
        		resolve();
        		/*End_c8o_function:CTS1559834148370*/
        
tplProjectName: mobilebuilder_tpl_7_7_0
useClickForTap: true
â†“Menu [mobile.components.UIDynamicMenu-1500890597895]: ðŸ— mobileMenus/Menu.yaml
â†“MenuLogin [mobile.components.UIDynamicMenu-1543518219237]: ðŸ— mobileMenus/MenuLogin.yaml
â†“MenuSelector [mobile.components.UIDynamicMenu-1543518260629]: ðŸ— mobileMenus/MenuSelector.yaml
â†“checkAndRegister [mobile.components.UIActionStack-1554977978587]: ðŸ— mobileSharedActions/checkAndRegister.yaml
â†“updateState [mobile.components.UIActionStack-1554989913269]: ðŸ— mobileSharedActions/updateState.yaml
â†“getTranslate [mobile.components.UIActionStack-1554994860699]: ðŸ— mobileSharedActions/getTranslate.yaml
â†“tick [mobile.components.UIActionStack-1554994873907]: ðŸ— mobileSharedActions/tick.yaml
â†“SharedSilder [mobile.components.UISharedComponent-1559049628991]: ðŸ— mobileSharedComponents/SharedSilder.yaml
â†“SlideItem [mobile.components.UISharedComponent-1559049729216]: ðŸ— mobileSharedComponents/SlideItem.yaml
â†“editorPage [mobile.components.PageComponent-1531323370377]: ðŸ— mobilePages/editorPage.yaml
â†“viewerPage [mobile.components.PageComponent-1537364775769]: ðŸ— mobilePages/viewerPage.yaml
â†“editElementPage [mobile.components.PageComponent-1531412002051]: ðŸ— mobilePages/editElementPage.yaml
â†“loginPage [mobile.components.PageComponent-1537532884984]: ðŸ— mobilePages/loginPage.yaml
â†“selectorPage [mobile.components.PageComponent-1537533843062]: ðŸ— mobilePages/selectorPage.yaml
â†“settingsPage [mobile.components.PageComponent-1539697882469]: ðŸ— mobilePages/settingsPage.yaml
â†“historyPage [mobile.components.PageComponent-1547734970073]: ðŸ— mobilePages/historyPage.yaml
â†“dropFilePage [mobile.components.PageComponent-1550679966506]: ðŸ— mobilePages/dropFilePage.yaml
â†“progressPage [mobile.components.PageComponent-1551263814512]: ðŸ— mobilePages/progressPage.yaml
â†“Theme [mobile.components.UITheme-1491635018260]: 
  comment: Global color themes can be customized here
  styleContent: 
    - xmlizable: 
      - â†‘classname: com.twinsoft.convertigo.beans.common.FormatedContent
      - com.twinsoft.convertigo.beans.common.FormatedContent: 
        â†’: |
          '// Ionic Variables and Theming. For more info, please see:
          // http://ionicframework.com/docs/v2/theming/ 
          $font-path: "../assets/fonts";
          
          @import "ionic.globals";
          @import "../assets/css/font-awesome.min.css";
          
          
          // Shared Variables
          // --------------------------------------------------
          // To customize the look and feel of this app, you can override
          // the Sass variables found in Ionic''s source scss files.
          // To view all the possible Ionic variables, see:
          // http://ionicframework.com/docs/v2/theming/overriding-ionic-variables/
          
          
          
          // Named Color Variables
          // --------------------------------------------------
          // Named colors makes it easy to reuse colors on various components.
          // It''s highly recommended to change the default colors
          // to match your app''s branding. Ionic uses a Sass map of
          // colors so you can add, rename and remove colors as needed.
          // The "primary" color is the only required color in the map.
          
          $colors: (
           		primary:    #488aff,
                  secondary:  #32db64,
                  danger:     #f53d3d,
                  light:      #f4f4f4,
                  dark:       #222,
                  white:		#ffffff,
                  convertigo: #0cbbe7,
          );
          
          
          
          // App iOS Variables
          // --------------------------------------------------
          // iOS only Sass variables can go here
          
          
          
          
          // App Material Design Variables
          // --------------------------------------------------
          // Material Design only Sass variables can go here
          
          
          
          
          // App Windows Variables
          // --------------------------------------------------
          // Windows only Sass variables can go here
          
          
          
          
          // App Theme
          // --------------------------------------------------
          // Ionic apps can have different themes applied, which can
          // then be future customized. This import comes last
          // so that the above variables are used and Ionic''s
          // default are overridden.
          
          @import "ionic.theme.default";
          
          
          // Ionicons
          // --------------------------------------------------
          // The premium icon font for Ionic. For more info, please see:
          // http://ionicframework.com/docs/v2/ionicons/
          
          @import "ionic.ionicons";
          
          
          // Fonts
          // --------------------------------------------------
          
          @import "roboto";
          @import "noto-sans";'
â†“Style [mobile.components.UIStyle-1491635462437]: 
  comment: You can add some global application styles here
  styleContent: 
    - xmlizable: 
      - â†‘classname: com.twinsoft.convertigo.beans.common.FormatedContent
      - com.twinsoft.convertigo.beans.common.FormatedContent: 
        â†’: |
          '.update-profile-modal .modal-wrapper{
          
          box-shadow: 0 16px 24px 2px rgba(0, 0, 0, 0.14), 0 6px 30px 5px rgba(0, 0, 0, 0.12), 0 8px 10px -5px rgba(0, 0, 0, 0.3);
          	
          
          }
          
          
          
          
          .image-upload > input
          {
              display: none;
          }
          .attach-doc
          {
              cursor: pointer;
          }
          .my-drop-zone { 
          	border: dotted 3px lightgray;
           }
          .nv-file-over { 
          	border: dotted 3px red;
          } /* Default class applied to drop zones on over */
          .another-file-over-class { 
          	border: dotted 3px green; 
          }
          .dot {
            height: 25px;
            width: 25px;
            background-color: #bbb;
            border-radius: 50%;
            display: inline-block;
          }
          
          .shadow{
          	box-shadow: 0 16px 24px 2px rgba(0, 0, 0, 0.14), 0 6px 30px 5px rgba(0, 0, 0, 0.12), 0 8px 10px -5px rgba(0, 0, 0, 0.3);
          
          border-left: 3px solid #488aff;
          }
          
          .shadow2{
          	box-shadow: 0 16px 24px 2px rgba(0, 0, 0, 0.14), 0 6px 30px 5px rgba(0, 0, 0, 0.12), 0 8px 10px -5px rgba(0, 0, 0, 0.3);
          border: 3px solid #488aff;
          }
          
          .cardPers{
          	position: relative;
              text-align: center;
          }
          
          .card-title {
              position: absolute;
              top: 36%;
              font-size: 2.0em;
              width: 100%;
              font-weight: bold;
              color: #fff;
            }
          
          .card-subtitle {
             font-size: 3.0em;
             position: absolute;
             bottom: 5%;
             width: 100%;
             color: #fff;
             text-align:center;
           }
            
            
          ::-webkit-scrollbar{
          
          display:none;
          
          }
          ion-scroll .scroll-content{
          -webkit-scrollbar: hidden;
          }
          
          
          
          .alertCustomCss {
              // text color for basic alerts
              color: white; 
              // alert modal page bg color. Warning this will remove the alert transparency
          
              button {
                  color: white !important; // button text color
                  background-color: color($colors, secondary, base) !important;
              }
          
              .alert-wrapper {
                  background-color: color($colors, dark, base); // bg color of alert content
              }
            }
            
          .changeToast {
          	.toast-wrapper {
          		text-align: center !important;
          		border-radius: 5px !important;
          		background: color($colors, primary);
          	}
          }
          .styledivred {
              background-color: #ffebee;
              margin-top: 2px;
              
              padding: 16px 17px;
          }
          .styledivnormal {
          
              margin-top: 2px;
              margin: 16px 17px;
          }
          .stylegenerictextred {
            background-color: transparent;
          border-bottom-color: #ff0000;
          box-shadow: inset 0 -1px 0 0 #ff0000;
          margin:0px;
          padding:0px;
          }
          .stylegenerictextnormal{
          	background-color: transparent;
          	border-bottom-color: #999999;
          	box-shadow: inset 0 -1px 0 0 #999999;
          	margin:0px;
          	padding:0px;
          	font-size: 16px;
          }
          
          ion-item {
            --border-color: var(--ion-color-danger, #f1453d);
          }
          
          .stylegenericcheckboxnormal {
          	background-color: transparent;
          	margin:0px;
          	padding:0px;
          	font-size: 16px;
          }
          
          
          .item-inner {
                box-shadow: none;
          
              }
          
          .content {
          	
          	
          	/* add some styling CSS rules here for the body of your app
          	   for example,
          	 		background-color: your color; 
          	 		background-image: url(some background image);
          	*/
          }
          
          .toolbar-background {
          	/* add some styling CSS rules here for the Headers and Footers
          	   for example,
          	 		background-color: your color; 
          	*/
          }
          .scroll-zoom-wrapper {
          height: 100% !important;
          }
          
          .formView {
          	width: 100%;
          	height: 100%;
          	border: 1px solid color($colors, primary, base);
          	border-radius: 4px;
          	background-color: #efefef;
          }
          
          .componentsView {
          	width: 100%;
          	height: 100%;
          	border: 1px solid color($colors, secondary);
          	border-radius: 4px;
          	background-color: #efefef;
          }
          
          .componentsView ion-list ion-list-header {
          	background-color: color($colors, secondary, #fff) !important;
          	color: #fff;
          /* 	font-weight: bold; */
          	border-radius: 8px !important;
          }
          
          .componentsView ion-list ion-item {
          /* 	background-color: color($colors, primary, #fff); */
          	margin: 5px 0;
          	border-radius: 12px !important;
          }
          
          .elementView {
          	border: 4px solid #808080;
          	border-radius: 12px;
          	background-color: #e4e4e4;
          }
          
          .containcol {
          	display: table;
              width: 100%;
          }
          .col {
          	display: table-cell;
              width:50%;
          }
          
          
          
          
          
          
           ion-grid {
              padding: 0 !important;
              ion-row {
                padding: 0 !important;
                ion-col {
                  padding: 0 !important;
          
                  ion-card {
                    padding: 0 !important;
                    ion-card-header {
                      margin-top: 1px !important;
                      margin-bottom: 1px !important;
                    }
                    ion-card-content {
                      margin-inside: 1px !important;
          
                      padding: 0 !important;
          
                      ion-list {
                        margin-inside: 1px !important;
                        padding: 0 !important;
          
                        ion-item {
                          margin-inside: 1px !important;
                          padding: 0 !important;
          
                          ion-row {
                            ion-col {
                              p {
                                color: color($colors, secondary, base) !important;
                                font-size: small !important;
                              }
                              color: color($colors, secondary, base) !important;
                              font-size: small !important;
          
                            }
          
                          }
          
                        }
          
                      }
          
                    }
                  }
                }
              }
            }
            .modal-wrapper {
           position: absolute;
                      top: 0;
                      left: 0;
                      right:0;
                      display: block;
                      width: 60%;
                      height: 60%;
                      top: 20%; 
               left: 20%; 
               right: 20%; 
          }'
â†“AppEvent [mobile.components.UIAppEvent-1554990556185]: 
  appEvent: onAppResume
  â†“InvokeSharedAction [mobile.components.UIDynamicInvoke-1554990732957]: 
    beanData: '{"ionBean":"InvokeAction"}'
    stack: C8Oforms.MobileApplication.Application.updateState
  â†“SetGlobal [mobile.components.UIDynamicAction-1559050043214]: 
    beanData: |
      '{
       "ionBean": "SetGlobalAction",
       "Property": "plain:_c8o_array_slide_img",
       "Value": "script:[''..\/assets\/images\/svg\/tel\/illus_tel_01.svg'',\r\n''..\/assets\/images\/svg\/tel\/illus_tel_02.svg'',\r\n''..\/assets\/images\/svg\/tel\/illus_tel_03.svg'']"
      }'
    isEnabled: false
  â†“CustomAction [mobile.components.UICustomAction-1559834148370]: 
    actionValue: 
      - xmlizable: 
        - â†‘classname: com.twinsoft.convertigo.beans.common.FormatedContent
        - com.twinsoft.convertigo.beans.common.FormatedContent: 
          â†’: |
            console.log(window.innerWidth);
            		    page.c8o.log.debug(event ? event.toString():'no event');
            		this.global.platform.name['0'] = 'mobile'; 
            		resolve();
            